web:
  image: harbour_crane:latest
  ports:
    - "3000:3000"
  volumes:
    # for system
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sbin/initctl:/sbin/initctl:ro
    - /etc/init:/etc/init
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
    # for save
    - /root/harbour-crane/app:/root/harbour-crane/app
    - /root/harbour-crane/compose:/root/harbour-crane/compose
    - /root/harbour-crane/upstart:/root/harbour-crane/upstart
    - /srv/docker/harbour-crane/log:/usr/src/app/log
    # for development
    - ~/Apps/harbour-crane:/usr/src/app
  environment:
    RAILS_ENV: development
    #RAILS_ENV: production
    VIRTUAL_HOST: harbour-crane.com
