web:
  image: harbour_crane:latest
  ports:
    - "3000:3000"
  volumes:
    # for system
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /root/Apps/Ui-Bibz:/root/Apps/Ui-Bibz
    #- /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
    #- /etc/init:/etc/init
    # for save
    - /root/harbour-crane/compose:/root/harbour-crane/compose
    - /srv/docker/harbour-crane/log:/usr/src/app/log
    # for debugging
    - /srv/docker/nginx/nginx.tmpl:/srv/docker/nginx/nginx.tmpl
    # for development
    - ~/Apps/harbour-crane:/usr/src/app
    - /root/harbour-crane/development.sqlite3:/root/harbour-crane/development.sqlite3
  environment:
    RAILS_ENV: development
    #RAILS_ENV: production
    VIRTUAL_HOST: harbour-crane.com
