version: '2'
services:
  web:
    #image: harbourcrane/harbour-crane:latest
    image: harbourcrane/harbour-crane:beta
    container_name: harbour-crane
    ports:
      - "81:3000"
    volumes:
      # for system
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /root/Apps/Ui-Bibz:/root/Apps/Ui-Bibz
      #- /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
      # for save
      #- ~/harbour-crane/composes:/root/harbour-crane/composes
      #- ~/harbour-crane/composes:/root/harbour-crane/composes
      #- ~/harbour-crane/db:/root/harbour-crane/db
      #- ~/harbour-crane/logs:/root/harbour-crane/logs
      #- ~/harbour-crane/proxy:/root/harbour-crane/proxy
      #- ~/harbour-crane/logs/harbour-crane:/usr/src/app/log
      #- ~/harbour-crane/composes:/root/harbour-crane/composes
      #- ~/harbour-crane/db:/root/harbour-crane/db
      #- ~/harbour-crane/logs:/root/harbour-crane/logs
      #- ~/harbour-crane/proxy:/root/harbour-crane/proxy
      #- ~/harbour-crane/proxy/nginx.tmpl:/root/harbour-crane/proxy/nginx.tmpl
      # - ~/harbour-crane/logs/harbour-crane:/usr/src/app/log
      - ~/harbour-crane/db/production.sqlite3:/usr/src/app/db/production.sqlite3
      # for development
      - ~/Apps/harbour-crane:/usr/src/app
      #- ~/harbour-crane/development.sqlite3:/root/harbour-crane/development.sqlite3
      #- ~/harbour-crane/production.sqlite3:/root/harbour-crane/production.sqlite3
    environment:
      RAILS_ENV: development
      #RAILS_ENV: production
      VIRTUAL_HOST: localhost

  data:
    image: busybox
    volumes:
      - /var/run/docker.sock
      - ~/harbour-crane

